services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_ingestion_app
    ports:
      - "${APP_HOST_PORT:-8000}:8000"
    environment:
      # Defaults point to compose services when not overridden
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@db:5432/job_ingestion}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      ENVIRONMENT: ${ENVIRONMENT:-development}
      PYTHONPATH: /app/src
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 25s
      timeout: 3s
      retries: 10
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: job_ingestion_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-job_ingestion}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: job_ingestion_redis
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
